### ISSUE TITLE
No omnifunc set in launch file

### ISSUE THREAD

**Issue by pylipp** [taketwo/vim-ros#24]
Omnicompletion in launch files does not work for me. I have YCM installed. 

When opening a launch file and typing `:set omnifunc?` I get `omnifunc=xmlcomplete#CompleteTags`. However, I'd like to make use of the omnicomplete function (`ros#launch_complete`) that this plugin provides. Do I have to set it manually? Also `:set ft?` returns `filetype=xml` but this should be overwritten by `vim-ros/syntax/roslaunch.vim`, right?

Using vim version 8.0 +python/dyn +python3/dyn on Ubuntu 16.04. Let me know if you need more info :)

**Comment by taketwo** [comment]
Seems like vim-ros does not recognize your file as a launch file, because it should set filetype to `roslaunch.xml` and omnifunc to `ros#launch_complete` automatically.

Detection happens as follows:
1. When a buffer is initialized, the function [`buf_init`](https://github.com/taketwo/vim-ros/blob/master/plugin/rosvim/__init__.py#L20) is called.
2. In the end it calls [`filetypes.init()`](https://github.com/taketwo/vim-ros/blob/master/plugin/rosvim/filetypes/__init__.py#L20), which goes through all supported types and checks if the buffer has this type.
3. The [`detect()`](https://github.com/taketwo/vim-ros/blob/master/plugin/rosvim/filetypes/launch.py#L120) function of the launch filetype should match the filename and return `True`.
4. Finally [`init()`](https://github.com/taketwo/vim-ros/blob/master/plugin/rosvim/filetypes/launch.py#L129) is called to setup `ft`, `omnicomplete`, etc.

You may try to insert debug printing statements here and there to check where the behavior deviates from the expected.

**Comment by pylipp** [comment]
Thanks for the detailed replay! I think it was a false alarm though, and the error is on my side. 

I dug into the code and found that `package` in [`Detect`](https://github.com/taketwo/vim-ros/blob/master/plugin/ros.vim#L78) is `None`. The issue is that the opened [launch file](https://github.com/pylipp/ros_temp_laser/blob/master/serial.launch) is not part of a ROS package but I rather have it for convenience in a project of mine to establish a ROS-based serial connection between a computer and an Arduino.

If that's not a common usecase for a launch file, I'll have to live without completion. OTOH it would be handy to have completion even here ;)

**Comment by taketwo** [comment]
You analysis is correct, the plugin works only with files in a ROS package. It is implemented this way to avoid runtime penalty on using Vim with non-ROS files. Also, it makes filetype detection simpler, e.g. if a file with `.msg` extension is in a ROS package, then it is definitely a ROS message description, not anything else.

I'd say your use-case is very uncommon; in order to support it we'd need quite a few changes in the way the plugin works... so it's a "won't fix", sorry :)
