### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by khssnv** [taketwo/vim-ros#35]
While [YouCompleteMe drops python2 support](https://github.com/ycm-core/YouCompleteMe#warning-support-for-python-2-has-been-dropped) it's hard to setup a right configuration with `vim-ros`. I've tried `py3` branch but it fails with some errors I can report if necessary. What can I do to make `vim-ros` work with `vim` built with `python3` only?

**Comment by taketwo** [comment]
The plugin itself is not a problem, we can make it agnostic to Python version. (In fact, if I remember correctly, `py3` branch already achieves that.) The real problem is that ROS packages that this plugin relies upon are built for Python 2.

As I noted in the other issue, give a try to Neovim which can have both Python versions installed.

**Comment by khssnv** [comment]
Ok, I see. Thank you for sharing, I'll switch to Neovim.
